[mongodb]
mongodb.roboticgear.shop
[catalogue]
catalogue.roboticgear.shop
[frontend]
frontend.roboticgear.shop
[redis]
redis.roboticgear.shop
[user]
user.roboticgear.shop
[cart]
cart.roboticgear.shop
[mysql]
mysql.roboticgear.shop
[rabbitmq]
rabbitmq.roboticgear.shop
[payment]
payment.roboticgear.shop
[shipping]
shipping.roboticgear.shop
[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321  # while exceuting it takes dynamically for all the components then it wont be necessary for executing adhoc command