- name: disabling the default nodejs
  ansible.builtin.command: dnf module disable nodejs -y
  
- name: enabling the nodejs
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: installing nodejs
  ansible.builtin.dnf:
    - name: nodejs
      state: present

- name: install dependencies
  community.general.npm:
    path: /app