- name: copy "{{ component }}" service to system directory
  ansible.builtin.copy:
    src: "{{ component }}.service.jinja2"
    dest: "/etc/systemd/system/{{ component }}.service"

- name: daemon reload
  ansible.buitlin.systemd_service:
    daemon_reload: true
    
    
- name: start the services
  ansible.builtin.services:
    name: "{{ component }}" 
    state: restarted   # even app is not running we can restart
    enable: yes