- name: copy catalogue service to system directory
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: daemon reload
  ansible.buitlin.systemd_service:
    daemon_reload: true
    
- name: start the services
  ansible.builtin.services:
    name: catalogue 
    state: restarted   # even app is not running we can restart
    enable: yes